"""
Claude Opus analyst for the county risk panel.

Pulls all relevant data for a single county from DuckDB, builds a structured
prompt, and streams the analysis back as SSE-formatted chunks.

No tool calls needed here — since the user clicked a specific county, we know
exactly what data to pull.  Tool use is reserved for NL Query and What-If Chat
where we don't know the data shape in advance.
"""

from __future__ import annotations

import json
import os
from typing import Generator

import anthropic
import duckdb

MODEL = "claude-opus-5"

SYSTEM = """You are a senior CDC epidemiological analyst specializing in \
vaccine-preventable disease surveillance and outbreak detection.

You are reviewing a measles hotspot risk score generated by a composite scoring \
model (vaccination coverage 40%, case surveillance 35%, network connectivity 25%). \
The audience is public health officials who need clear, actionable intelligence.

Format your response as plain text using this structure:
RISK SUMMARY
[2-3 sentences giving the bottom-line assessment]

KEY RISK DRIVERS
[Bullet points using • identifying the specific factors most driving the score, \
with the actual numbers. Focus on what is abnormal compared to state or national \
norms. Be direct — do not hedge when the data clearly shows elevated risk.]

COMPARABLE CONTEXTS
[1-2 sentences placing this county in context relative to other flagged counties \
or the 2025 Gaines County outbreak trajectory, if relevant.]

RECOMMENDED INTERVENTIONS
[Numbered list of 3-5 concrete, prioritized public health actions appropriate \
for this specific risk profile. Reference the specific sub-scores driving each \
recommendation.]

Keep the total response under 450 words. Use specific numbers from the data. \
Do not use markdown formatting."""


def _build_context(fips: str, con: duckdb.DuckDBPyConnection) -> dict | None:
    geo = con.execute(
        "SELECT county_name, full_name, population FROM geographies WHERE fips = ?",
        [fips],
    ).fetchone()
    if not geo:
        return None

    cov = con.execute(
        """SELECT mmr_coverage_pct, medical_exempt_pct, nonmedical_exempt_pct, enrolled
           FROM vaccination_coverage WHERE fips = ? ORDER BY school_year DESC LIMIT 1""",
        [fips],
    ).fetchone()

    surv = con.execute(
        """SELECT confirmed_cases, suspect_cases, wastewater_signal, lab_positivity_pct
           FROM surveillance WHERE fips = ? ORDER BY report_date DESC LIMIT 1""",
        [fips],
    ).fetchone()

    net = con.execute(
        """SELECT mobility_index, religious_community_idx, border_adjacent
           FROM network_metrics WHERE fips = ? ORDER BY metric_date DESC LIMIT 1""",
        [fips],
    ).fetchone()

    score = con.execute(
        """SELECT composite_score, coverage_score, surveillance_score, network_score,
                  risk_tier, score_components
           FROM hotspot_scores WHERE fips = ? ORDER BY score_date DESC LIMIT 1""",
        [fips],
    ).fetchone()

    # Find nearby high-risk counties (same state, score ≥ 50)
    nearby = con.execute(
        """SELECT g.county_name, hs.composite_score, hs.risk_tier
           FROM hotspot_scores hs
           JOIN geographies g ON hs.fips = g.fips
           WHERE g.state_abbr = (SELECT state_abbr FROM geographies WHERE fips = ?)
             AND hs.fips != ?
             AND hs.composite_score >= 50
           ORDER BY hs.composite_score DESC LIMIT 4""",
        [fips, fips],
    ).fetchall()

    # State median for reference
    state_stats = con.execute(
        """SELECT AVG(vc.mmr_coverage_pct), AVG(hs.composite_score)
           FROM vaccination_coverage vc
           JOIN hotspot_scores hs ON vc.fips = hs.fips
           JOIN geographies g ON vc.fips = g.fips
           WHERE g.state_abbr = (SELECT state_abbr FROM geographies WHERE fips = ?)""",
        [fips],
    ).fetchone()

    components = json.loads(score[5]) if score and score[5] else {}

    return {
        "county_name": geo[0],
        "full_name": geo[1],
        "population": geo[2],
        "mmr_coverage_pct": cov[0] if cov else None,
        "medical_exempt_pct": cov[1] if cov else None,
        "nonmedical_exempt_pct": cov[2] if cov else None,
        "enrolled": cov[3] if cov else None,
        "confirmed_cases": surv[0] if surv else 0,
        "suspect_cases": surv[1] if surv else 0,
        "wastewater_signal": surv[2] if surv else 0.0,
        "lab_positivity_pct": surv[3] if surv else 0.0,
        "mobility_index": net[0] if net else None,
        "religious_community_idx": net[1] if net else None,
        "border_adjacent": bool(net[2]) if net else False,
        "composite_score": score[0] if score else None,
        "coverage_score": score[1] if score else None,
        "surveillance_score": score[2] if score else None,
        "network_score": score[3] if score else None,
        "risk_tier": score[4] if score else None,
        "coverage_gap_score": components.get("coverage_gap_score"),
        "exemption_score": components.get("exemption_score"),
        "incidence_score": components.get("incidence_score"),
        "wastewater_score": components.get("wastewater_score"),
        "mobility_score": components.get("mobility_score"),
        "community_score": components.get("community_score"),
        "nearby_high_risk": [
            {"county": r[0], "score": r[1], "tier": r[2]} for r in nearby
        ],
        "state_avg_coverage": round(state_stats[0], 1) if state_stats[0] else None,
        "state_avg_score": round(state_stats[1], 1) if state_stats[1] else None,
    }


def _build_prompt(ctx: dict) -> str:
    nearby_text = (
        ", ".join(f"{r['county']} ({r['score']:.0f}, {r['tier']})" for r in ctx["nearby_high_risk"])
        or "None above 50"
    )

    return f"""Analyze the measles hotspot risk profile for {ctx['county_name']} County \
(population {ctx['population']:,}).

COMPOSITE HOTSPOT SCORE: {ctx['composite_score']:.1f}/100 — {ctx['risk_tier']}
State average composite score: {ctx['state_avg_score']}

LAYER 1 — Vaccination Coverage & Exemption (40% weight): {ctx['coverage_score']:.1f}/100
  • MMR school-year coverage: {ctx['mmr_coverage_pct']:.1f}% \
(herd immunity threshold for measles: 95%)
  • Non-medical exemptions: {ctx['nonmedical_exempt_pct']:.1f}% of enrolled students
  • Medical exemptions: {ctx['medical_exempt_pct']:.2f}%
  • Enrolled students: {ctx['enrolled']:,}
  • Coverage gap sub-score: {ctx['coverage_gap_score']:.1f}/60
  • Exemption pressure sub-score: {ctx['exemption_score']:.1f}/40
  • State average MMR coverage: {ctx['state_avg_coverage']}%

LAYER 2 — Case & Lab Surveillance (35% weight): {ctx['surveillance_score']:.1f}/100
  • Confirmed measles cases (last 90 days): {ctx['confirmed_cases']}
  • Suspect cases: {ctx['suspect_cases']}
  • Wastewater environmental signal: {ctx['wastewater_signal']:.2f} (scale 0–1)
  • Lab positivity: {ctx['lab_positivity_pct']:.1f}%
  • Incidence sub-score: {ctx['incidence_score']:.1f}/60

LAYER 3 — Network & Connectivity (25% weight): {ctx['network_score']:.1f}/100
  • Mobility index: {ctx['mobility_index']:.2f} (scale 0–1; higher = more connected)
  • Religious/homogeneous community clustering index: {ctx['religious_community_idx']:.2f}
  • Border county: {ctx['border_adjacent']}
  • Community clustering sub-score: {ctx['community_score']:.1f}/40

OTHER HIGH-RISK COUNTIES IN THIS STATE (score ≥ 50):
{nearby_text}

Provide your analysis now."""


def stream_analyst(fips: str, con: duckdb.DuckDBPyConnection) -> Generator[str, None, None]:
    """Yield SSE-formatted events: text deltas, then [DONE]."""
    ctx = _build_context(fips, con)
    if ctx is None:
        yield f"data: {json.dumps({'type': 'error', 'message': f'County {fips} not found'})}\n\n"
        return

    api_key = os.getenv("ANTHROPIC_API_KEY", "")
    if not api_key or api_key == "your_key_here":
        yield f"data: {json.dumps({'type': 'error', 'message': 'ANTHROPIC_API_KEY not set in backend/.env'})}\n\n"
        return

    client = anthropic.Anthropic(api_key=api_key)

    # Emit a metadata event so the frontend knows the county name
    yield f"data: {json.dumps({'type': 'meta', 'county': ctx['county_name'], 'score': ctx['composite_score'], 'tier': ctx['risk_tier']})}\n\n"

    try:
        with client.messages.stream(
            model=MODEL,
            max_tokens=1600,
            system=SYSTEM,
            messages=[{"role": "user", "content": _build_prompt(ctx)}],
            thinking={"type": "adaptive"},
        ) as stream:
            for text in stream.text_stream:
                yield f"data: {json.dumps({'type': 'text', 'delta': text})}\n\n"
    except anthropic.APIError as exc:
        yield f"data: {json.dumps({'type': 'error', 'message': str(exc)})}\n\n"
        return

    yield "data: [DONE]\n\n"
